name: Code development flow
concurrency: ${{ github.event.repository.name }}-dev
'on':
    push:
        branches:
            - dev
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install and build
              uses: ./.github/actions/build
            - name: Run quality checks
              uses: ./.github/actions/quality
            - name: Deploy to Firebase Hosting
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VERSATIL_DEV }}'
                  channelId: live
                  projectId: '${{ secrets.PROJECT_ID_DEV }}'
              env:
                  FIREBASE_CLI_EXPERIMENTS: webframeworks
